gitlab-ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -63,22 +63,15 @@ deploy_local:
     - echo "Checking Docker version"
     - docker --version  # Affiche la version de Docker
 
-    # Étape : Arrêter et supprimer le conteneur existant si nécessaire
-    - echo "Arrêt et suppression du conteneur existant (s'il existe)..."
-    - docker stop $CONTAINER_NAME || true
-    - docker rm $CONTAINER_NAME || true
-
-    - echo "Checking if port 8000 is in use..."
-    # Vérifier si le port 8000 est occupé
-    - if netstat -tuln | grep ':8000' > /dev/null; then
-        echo "Port 8000 is in use. Killing the process...";
-        PROCESS_ID=$(netstat -tulnp | grep ':8000' | awk '{print $6}' | cut -d'/' -f1);
-        kill -9 $PROCESS_ID || true;
+    - |
+      echo "Checking if port 8000 is in use locally..."
+      if lsof -i :8000 > /dev/null 2>&1; then
+        echo "Port 8000 is in use. Attempting to free it...";
+        PID=$(lsof -ti :8000);
+        kill -9 $PID || echo "Failed to kill process on port 8000";
       else
         echo "Port 8000 is free.";
       fi
-    - echo "Checking Docker containers using port 8000..."
-    # Vérifier et arrêter les conteneurs Docker utilisant le port 8000
     - docker ps -q --filter "publish=8000" | xargs -r docker stop
     - docker ps -q --filter "publish=8000" | xargs -r docker rm
 
